### ISSUE TITLE
It shows "cannot set timeout for src"

### ISSUE THREAD

**Issue by Lightmani** [HirbodBehnam/PortForwarder#4]
While I use this tool to relay port, it works well,
But the log shows many lines like "2020/05/29 18:30:29 [cannot set timeout for src]"

I don't know what this line means.
Can you give me some advice ?

PS:
Some of my config was 
{
"SaveDuration":600,"
Timeout":10
}

**Comment by Lightmani** [comment]
While I change the timeout value to 120
It still shows

2020/05/29 18:57:16 [cannot set timeout for src]
2020/05/29 18:57:16 [Error on copyBuffer(Usually happens): set tcp 192.168.1.1:35576: use of closed network connection]

**Comment by HirbodBehnam** [comment]
Hello
I cannot reproduce this and this kinda looks normal (unless you have problems connecting to your destination). Also note that the line below the `cannot set timeout for src` is the reason of it.
What the logs are saying is that the program is trying to set the timeout on a connecting that is closed.

Do you have any problems connecting to your destination via the forwarder?

**Comment by HirbodBehnam** [comment]
I pushed 5163cacc39d08bcbb52c2c470169747517d405e5 that checkes the error message of the cannot set timeout before reporting it.

**Comment by Lightmani** [comment]
Cool !
The new version stop to report it.
Thanks for your replying and help !
